services:
  sni-proxy:
    image: traefik:v3.6.2
    command:
      - "--api.insecure=true"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.traefik.address=:8082"
      - "--providers.http.endpoint=http://aggregator:8080/traefik-config"
      - "--providers.http.pollInterval=10s"
      - "--log.level=INFO"
      - "--accesslog=true"
    ports:
      - "443:443"
      - "80:80"
      - "8082:8082"
    depends_on:
      aggregator:
        condition: service_healthy

  aggregator:
    build: .
    volumes:
      - ./config.yml:/app/config.yml:ro
    ports:
      - "8080:8080"
    depends_on:
      - downstream-traefik-1
      - nginx
    healthcheck:
      test: ["CMD", "/app/healthcheck"]
      interval: 30s
      timeout: 3s
      retries: 5
      start_period: 5s

  # Example downstream Traefik
  downstream-traefik-1:
    image: traefik:v3.6.2
    command:
      - "--api.insecure=true"
      - "--entrypoints.websecure.address=:8443"
      - "--entrypoints.web.address=:808"
      - "--entrypoints.traefik.address=:8081"
      - "--providers.docker=true"
      - "--log.level=INFO"
      - "--accesslog=true"
    ports:
      - "8081:8081"
      - "808:808"
      - "8443:8443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  nginx:
    image: nginx:latest
    ports:
      - "82:80"
    labels:
      - "traefik.http.routers.nginx.rule=Host(`nginx.localhost`)"
      - "traefik.http.routers.nginx.entrypoints=web,websecure"
      - "traefik.http.routers.nginx.tls=true"
